apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-traffic
spec:
  podSelector: {}  # Tüm pod'ları seçer
  policyTypes:
  - Ingress
  - Egress
  ingress:          # Tüm gelen trafiğe izin verir
  - {}
  egress:           # Tüm giden trafiğe izin verir
  - {}
